updated weather skill to answer most queries
fossasia/susi_skill_data pull request #127
Opened 2017-06-10 17:08 UTC by AliAyub007

Fixes issue #122 

Changes:
Added skill to answer different queries related weather in different way.

Screenshots for the change: 

![weather1](https://user-images.githubusercontent.com/25840461/27004790-5082ff0e-4e29-11e7-9638-9359912475b6.PNG)

![weather2](https://user-images.githubusercontent.com/25840461/27004794-592a76d2-4e29-11e7-8278-dd665c4b27eb.PNG)

2017-06-11 05:59 UTC, hpdang requested changes
I wonder if we can use the specific weather API instead taking wolframalpha for everything. the openweathermap.org doesn't work? Accuweather or Weatherunderground (wunderground) also offer free API for developers

2017-06-11 06:06 UTC, AliAyub007 commented
@hpdang openweather was not giving accurate responses and weatherunderground has limited number of api calls i.e 500 API calls per day and so do other APIs. If I will make a skill with it now it will work fine but as soon we get more number of users our skill will go down and we might have to pay for APIs which is not a best way.

2017-06-13 13:16 UTC, hpdang commented
@AliAyub007 please ask fellow developers to review your PR. Don't forget our peer review practice. Thank you.

2017-06-13 16:03 UTC, AliAyub007 commented
@Manveer695 @saurabhjn76 @dynamitechetan  Kindly review this PR Thank you.

2017-06-13 17:21 UTC, saurabhjn76 commented on models/general/knowledge/en/weather_information.txt
> +I love snow too but I am sad I can't throw snow balls
I think answer should be different in this case or "too" can be removed

2017-06-13 17:21 UTC, saurabhjn76 commented on models/general/knowledge/en/weather_information.txt
> +
Above skills do not give weather information, maybe we should change it to some other file?

2017-06-13 17:21 UTC, saurabhjn76 commented on models/general/knowledge/en/weather_information.txt
> +weather tomorrow|what is weather tomorrow|what will be the weather tomorrow|what is weather report of tomorrow|Give me weather report of tomorrow|Tell me about weather tomorrow|Tell me about about we
Is it snowing today Is it snowing missing optional symbol (|)

2017-06-13 18:21 UTC, Manveer695 commented on models/general/knowledge/en/weather_information.txt
> +!console:Sunset time in $1$ is $sunrise$
I think here it should be sunrise.

2017-06-13 18:41 UTC, Manveer695 approved these changes

2017-06-15 23:43 UTC, merged