Fixes issue #109: Covering more currency conversions to bitcoin than before.
fossasia/susi_skill_data pull request #132
Opened 2017-06-13 07:20 UTC by Manveer695

Fixes issue #109 i.e. Adding skill to tell latest exchange rates for currencies to bitcoin

Screenshots for the change: 
<img width="507" alt="primage" src="https://user-images.githubusercontent.com/20307535/27070461-bb75e8bc-5036-11e7-88ce-86b3637346d0.PNG">

dream link:
dream.susi.ai/p/currencytobitcoin

2017-06-13 08:30 UTC, saurabhjn76 approved these changes

2017-06-14 05:53 UTC, Manveer695 commented
Please review @aliayub007 @chashmeetsingh @betterclever @madhavrathi. Thank you!

2017-06-15 06:34 UTC, AliAyub007 commented on models/general/knowledge/en/currency_to_bitcoin.txt
> +convert bitcoin to russian ruble | convert btc to rub| convert btc to russian ruble | convert btc to russian ruble | btc to russian ruble |btc to russian ruble |btc to russian ruble |what is latest e
There is some redundancy in questions kindly fix that 
like btc to russian ruble |btc to russian ruble

2017-06-17 11:52 UTC, hpdang requested changes
@Manveer695 please add everything you have here into the existing bitcoin skill. https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/bitcoin.txt 

All bitcoin related stuff will go there. Please do so and delete this file. Thank you.

2017-06-17 17:00 UTC, Manveer695 commented
@hpdang Ok, mam. I have done the required steps, please review again. Thanks!

2017-06-18 03:25 UTC, merged