partly Fixes #134:Added skill for converting binary into decimal
fossasia/susi_skill_data pull request #136
Opened 2017-06-13 20:07 UTC by madhavrathi

partly fixes issue #134 

Changes: Added skill for binary to decimal conversion

Etherpad link: http://dream.susi.ai/p/binary_to_decimal
Screenshots for the change: 
![hy](https://cloud.githubusercontent.com/assets/22375731/26759587/83da77a6-491f-11e7-8e47-6a071e8ec11e.png)

2017-06-15 07:23 UTC, Manveer695 commented on models/general/problemsolving/en/binaryToDecimal.txt
> +convert * into decimal | decimal of *
can you add a question like - convert * to decimal. Thanks!

2017-06-18 03:55 UTC, hpdang requested changes
@madhavrathi please make sure, there's always at least 2 approved reviews. And could you please add this into your previous skill, we don't need two different skills for this https://github.com/fossasia/susi_skill_data/blob/master/models/general/problemsolving/en/decimalToBinary.txt

2017-06-18 06:41 UTC, madhavrathi commented
@hpdang Made the required changes.
@dynamitechetan @saurabhjn76 @Manveer695 please review this PR.
Thanks

2017-06-18 17:10 UTC, Laughing-Boy approved these changes

2017-06-18 17:12 UTC, jyoth1raditya commented
@madhavrathi ,Please add more questions

2017-06-20 19:11 UTC, madhavrathi commented
@jyoth1raditya Please review !
Thanks

2017-06-25 06:43 UTC, merged