Fixes #130: Create skills from Loklak
fossasia/susi_skill_data pull request #137
Opened 2017-06-14 02:38 UTC by rishiraj824

Fixes issue #130 

Changes: 
- Added queries to get tweets about a query

Dreampad Link : http://dream.susi.ai/p/loklak

Screenshots for the change: 
![screenshot from 2017-06-14 08 03 16](https://user-images.githubusercontent.com/11540785/27113099-9243e9ec-50d8-11e7-959f-35dbb563cf05.png)

2017-06-15 07:11 UTC, Manveer695 approved these changes

2017-06-16 00:22 UTC, AliAyub007 commented on models/general/knowledge/en/loklak.txt
> +tweets about *| tweet *| 5 tweets about *|Latest tweets about *
I suggest you should add more questions to it to make this skill responsive like
Give me tweets about * 
Tell me tweets about *
what are latest tweets about * 
what are the latest tweets about * 
Can you give me tweets about * 
I want tweets about * 
I need tweets about * 

and similarly more like this.

2017-06-17 05:46 UTC, rishiraj824 commented
@AliAyub007 Please review

2017-06-17 05:50 UTC, AliAyub007 approved these changes
Kindly squash the commits 👍

2017-06-17 07:23 UTC, rishiraj824 commented
@AliAyub007 Done

2017-06-17 09:37 UTC, AliAyub007 approved these changes

2017-06-17 11:28 UTC, hpdang requested changes
@rishiraj824 good start. But please consider how to name your skill. Does this skill provide any information about loklak? loklak is just another API like wolframalpha. Your current questions are fine but please think of more things you can do with tweets. Can you tell people's favorite drama this month/week from the tweets? can you tell most view news articles? anything about celebrities? and can we find a twitter handle of a person based on his/her full name, or name + company?  Please make it your focus of Milestone 7. Thanks.

2017-06-18 13:15 UTC, rishiraj824 commented
@hpdang Sure. I'll try and see how we can get all this data as a response.

2017-06-20 05:13 UTC, rishiraj824 commented
@hpdang Updated the PR with some more options
 - One can find tweets from particular users
![screenshot from 2017-06-20 10 37 50](https://user-images.githubusercontent.com/11540785/27317609-33399998-55a5-11e7-8c33-185742050f2c.png)
-  One can find tweets having certain user mentions
![screenshot from 2017-06-20 10 39 31](https://user-images.githubusercontent.com/11540785/27317611-362bf614-55a5-11e7-87ae-f372f452103e.png)

2017-06-22 16:32 UTC, dynamitechetan approved these changes

2017-06-25 06:37 UTC, hpdang commented
@rishiraj824 thank you. Can you still think of more things we can do with Loklak data please!

2017-06-25 06:37 UTC, merged