Enhanced border length questions
fossasia/susi_skill_data pull request #170
Opened 2017-06-19 19:07 UTC by AliAyub007

Fixes issue #119 

Changes: 
Added more possible questions to border.txt file

2017-06-19 19:26 UTC, saurabhjn76 approved these changes
good work :+1: , please change the word fixes in the message as there are other skills also which needs to be enhanced

2017-06-20 07:26 UTC, Laughing-Boy approved these changes

2017-06-20 07:56 UTC, mariobehling requested changes
Can we also have things like:
* How long is the border of ...
* How long is the border between country a and country b?
* What are the countries bordering country x?

2017-06-20 07:58 UTC, AliAyub007 commented
@mariobehling Sure I will add these too.

2017-06-21 17:00 UTC, dynamitechetan approved these changes

2017-06-25 06:10 UTC, merged