Update user_positive_expression.txt
fossasia/susi_skill_data pull request #204
Opened 2017-07-01 12:05 UTC by jyoth1raditya

Fixes issue #185, updated with new questions.

Etherpad Link:

2017-07-02 15:17 UTC, hpdang approved these changes

2017-07-03 08:01 UTC, jyoth1raditya commented
@DravitLochan @dynamitechetan @saurabhjn76 please review

2017-07-03 08:22 UTC, saurabhjn76 approved these changes

2017-07-03 09:32 UTC, DravitLochan requested changes

2017-07-03 09:32 UTC, DravitLochan commented on models/general/smalltalk/en/user_positive_expression.txt
> +Great Reply|Good Reply|Thanks|you are great|you are good|You are smart|superb reply|amazing reply|wonderful reply|incredible reply|unbelievable reply
add good job

2017-07-03 09:32 UTC, DravitLochan commented on models/general/smalltalk/en/user_positive_expression.txt
> +You are beautiful|you are angel|you are intelligent|you are human|you are god|
Let's club it with line 15.

2017-07-03 09:32 UTC, DravitLochan commented on models/general/smalltalk/en/user_positive_expression.txt
>  hope to see you again|see you again
see you soon

2017-07-03 16:45 UTC, dynamitechetan approved these changes

2017-07-04 01:03 UTC, jyoth1raditya commented
@hpdang Please Review and merge this PR.

2017-07-04 11:00 UTC, merged