plot, rating and other info about movie, series added
fossasia/susi_skill_data pull request #213
Opened 2017-07-04 07:05 UTC by Manveer695

Fixes issue #139 

Etherpad Link: http://dream.susi.ai/p/infomovies

Screenshots for the change: 
<img width="524" alt="prrating3" src="https://user-images.githubusercontent.com/20307535/27818837-299ba226-60b5-11e7-9194-23038de799ef.PNG">
<img width="526" alt="prinfo2" src="https://user-images.githubusercontent.com/20307535/27818846-34db594c-60b5-11e7-8232-ec885bdf6b29.PNG">
<img width="521" alt="prplot1" src="https://user-images.githubusercontent.com/20307535/27818850-3a99578a-60b5-11e7-847a-f3cd7af54e0c.PNG">

2017-07-04 07:06 UTC, Manveer695 commented
@dynamitechetan @AliAyub007 @betterclever @chiragw15 @DravitLochan Please review it guys! Thank you.

2017-07-05 17:16 UTC, dynamitechetan approved these changes

2017-07-05 17:35 UTC, saurabhjn76 approved these changes

2017-07-06 04:39 UTC, Laughing-Boy approved these changes

2017-07-06 04:43 UTC, DravitLochan approved these changes

2017-07-06 06:19 UTC, AliAyub007 approved these changes

2017-07-08 21:18 UTC, mariobehling requested changes
Please ensure all examples a real and complete question, e.g. What is the rating of Game of Thrones?

2017-07-11 07:41 UTC, Laughing-Boy approved these changes

2017-07-17 00:26 UTC, merged