Added description in skill for problem-solving and small talks category.
fossasia/susi_skill_data pull request #239
Opened 2017-07-20 18:00 UTC by DravitLochan

Partially Fixes issue #234
Added description in skill for problem-solving and small talks category.

2017-07-20 18:00 UTC, DravitLochan commented
@madhavrathi @dynamitechetan @saurabhjn76 @Manveer695 @chiragw15 @betterclever @chashmeetsingh Please review!

2017-07-20 18:07 UTC, dynamitechetan approved these changes

2017-07-20 19:45 UTC, madhavrathi approved these changes

2017-07-20 20:11 UTC, saurabhjn76 approved these changes

2017-07-21 00:02 UTC, chashmeetsingh approved these changes

2017-07-21 06:23 UTC, Manveer695 approved these changes

2017-07-29 23:05 UTC, mariobehling commented
Please resolve conflicts and add images for each skill.

2017-07-29 23:07 UTC, mariobehling commented on models/general/problemsolving/en/advanced_math.txt
> +!description : Ask for derivative of simple Mathematical functions
Why is there a space in front of ":"? Please fix this in all files.

2017-08-03 06:05 UTC, mariobehling commented
@DravitLochan Please finalize the version of this PR.

* Use the latest format and ensure all skills you are working on have a square image that is hosted on the repo

* Ensure you stick to the latest format
![screenshot from 2017-08-03 08-01-25](https://user-images.githubusercontent.com/1583873/28908183-6f112126-7822-11e7-8326-5663bf67d71e.png)

2017-08-03 14:56 UTC, dynamitechetan reviewed
Please resolve conflicts

2017-08-05 10:12 UTC, mariobehling requested changes
Please follow format and add all details.

2017-08-05 14:43 UTC, DravitLochan commented
On to it.

2017-08-05 21:22 UTC, DravitLochan commented
@mariobehling This PR is now ready to merge. @saurabhjn76 is already working to add images in problem-solving. Once this PR is merged, He may open one for images. Please review and merge. Thanks!

2017-08-05 23:03 UTC, merged