Basic questions asked to susi added
fossasia/susi_skill_data pull request #244
Opened 2017-07-27 06:47 UTC by Manveer695

Fixes issue #119 i.e. add more questions to skills

Etherpad Link: http://dream.susi.ai/p/basics

Screenshots for the change: 
<img width="518" alt="susiskill1" src="https://user-images.githubusercontent.com/20307535/28657590-7c01b646-72c5-11e7-8961-1edf370eb660.PNG">
<img width="525" alt="susiskill2" src="https://user-images.githubusercontent.com/20307535/28657591-7c13a964-72c5-11e7-8bbc-aaa10db04669.PNG">
<img width="520" alt="susiskill3" src="https://user-images.githubusercontent.com/20307535/28657592-7c2247a8-72c5-11e7-97ed-76fb133c60f6.PNG">

2017-07-27 06:47 UTC, Manveer695 commented
@AliAyub007 @betterclever @dynamitechetan @madhavrathi @chashmeetsingh Please review!

2017-07-30 06:12 UTC, madhavrathi approved these changes
Looks good to me.

2017-07-30 06:33 UTC, dynamitechetan approved these changes

2017-07-30 06:35 UTC, mariobehling requested changes
Fix spelling and punctuation according to International English.

2017-07-30 06:46 UTC, mariobehling commented
@madhavrathi @dynamitechetan Aren't you seeing the issues with spelling and syntax? How come you approve that?

2017-07-30 07:24 UTC, madhavrathi commented
@mariobehling I am very sorry but are you referring to this reply:  "Awwwwwww, Muaaaah!". This was an expression so I thought there was no issue with this. Will take care next time.

2017-07-30 07:32 UTC, Manveer695 commented
@mariobehling Sorry for the answer to "i love you" query. please state any other questions or answers having problems so that i can fix that right away. Sorry for not being able to spot them.

2017-07-30 12:10 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +!description: to remember its own name
The description should actually describe things in several sentences and correct spelling and syntax.

2017-07-30 12:11 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
>  If I tell you, I'll have to kill you | That'll be a secret :D
Why is there not full stop at the end?

2017-07-30 12:11 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +Social Universe Super Intelligence(SUSI) at your service
+Social Universe Super Intelligence (SUSI)

Please follow proper syntax!

2017-07-30 12:12 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +!example: are you susi
Proper spelling and syntax!

2017-07-30 12:12 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +!description: querying about the name
Is that a sentence? Add a proper description!

2017-07-30 12:12 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +!example: please fuck off
Who would say "please" here?

2017-07-30 12:12 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +!example: please fuck off
Add correct syntax!

2017-07-30 12:13 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +Please don't talk to me like that | Do you really think I deserved that!
add proper syntax!

2017-07-30 12:13 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +i love your * susi | i love you susi | i love you | i love your * | i am in love with you | i am in love with your * | love you
Since when do you write "i" in small letters? Correct all grammar, spelling, syntax errors!

2017-07-30 12:15 UTC, mariobehling commented on models/general/smalltalk/en/aboutsusi.txt
> +The people who contribute to me become like me. So checkout https://www.github.com/fossasia/susi_server and contribute if you want to!
Don't show links as links! Make them how you would say it and make SUSI repository on GitHub into a link to https://www.github.com/fossasia/susi_server!

"So, checkout the SUSI repository on Github and start contributing!"

2017-07-30 12:16 UTC, mariobehling commented
I wonder, what is faster - to write the whole thing again from scratch or to point every single error in this to you. It is making me sad, that I need to follow up on so small details. We are now in the 3 term and we are expecting more. I am sorry with such low quality commits you will not be able to pass the third term.

2017-07-30 12:16 UTC, mariobehling commented
I just commented on a few errors. There are many more. Fix all of them, please!

2017-07-30 12:18 UTC, mariobehling commented
Stick to correct English!

2017-07-31 09:00 UTC, Manveer695 commented
@mariobehling Sorry for the grammar mistakes. I have tried my best to resolve all the errors and increase the quality of the commit. Thanks a lot for the review.

2017-07-31 12:22 UTC, mariobehling commented
Improve spelling and follow International English!
e.g. what is your name ? -> What is your name?

I wonder how many iterations are needed.

2017-08-01 01:34 UTC, Manveer695 commented
@mariobehling Ok sure, resolved it. Thank you, sir.

2017-08-03 06:03 UTC, mariobehling commented
Please also handle skills in the latest format style and resolve conflicts.

![screenshot from 2017-08-03 08-01-25](https://user-images.githubusercontent.com/1583873/28908155-2941dad2-7822-11e7-9533-4394a9944e77.png)

2017-08-03 19:35 UTC, Manveer695 commented
@mariobehling Updated the PR according to the new format. I am following Alexa and getting help from @saurabhjn76 for writing a developer privacy policy and terms of use for the skill. Still working on it, so those fields are left blank. Otherwise, the PR is updated. Thank you for the review.

2017-08-03 22:00 UTC, mariobehling commented
Thank you.

2017-08-03 22:01 UTC, merged